### ISSUE TITLE
operator- isn't const operator

### ISSUE THREAD

**Issue by RandomGuy1520** [LucasDu-lab/contest-templates#1]
bign operator-(const bign b)
{
	Int res;
	res.len = max(len, b.len);
	for (int i = 0; i < res.len; i++)
	{
		if (res.nums[i] < b.nums[i])
		{
			nums[i + 1]--; // Is this a typo?
			nums[i] += 10; // Is this a typo?
		}
		res.nums[i] = nums[i] - b.nums[i];
	}
	while (res.nums[res.len - 1] == 0 && res.len > 1)
		res.len--;
	return res;
}

**Comment by LucasDu-lab** [comment]
try to run and test the template, it should be ok
